version: '3.4'

services:
  web:
    build: .
    command: bash -c "python venv/bin/debugpy --wait-for-client --listen 0.0.0.0:5678 -m uvicorn rental_app.asgi:application --host 0.0.0.0 --port 8000"
    container_name: rental_app
    volumes:
      - .:/rental_app
    ports:
      - "8000:8000"
      - "5678:5678"
    