# Generated by Django 4.1.7 on 2023-03-25 14:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="property",
            old_name="reviews",
            new_name="property_review",
        ),
        migrations.AddField(
            model_name="property",
            name="rating",
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="review",
            name="pub_date",
            field=models.DateTimeField(
                default=django.utils.timezone.now, verbose_name="date published"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="review",
            name="rented_duration",
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="review",
            name="ending_rent",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="review",
            name="starting_rent",
            field=models.IntegerField(default=0),
        ),
    ]
