# Generated by Django 4.1.7 on 2023-04-01 14:49

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("main", "0002_rename_reviews_property_property_review_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="review",
            old_name="reviewed_property",
            new_name="property",
        ),
        migrations.RemoveField(
            model_name="property",
            name="property_review",
        ),
        migrations.RemoveField(
            model_name="property",
            name="rating",
        ),
        migrations.AddField(
            model_name="review",
            name="ending_rent_month_year",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="review",
            name="rented_duration_in_months",
            field=models.IntegerField(
                blank=True,
                null=True,
                validators=[django.core.validators.MaxValueValidator(9999)],
            ),
        ),
        migrations.AddField(
            model_name="review",
            name="starting_rent_month_year",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="review",
            name="title",
            field=models.CharField(default="Review", max_length=100),
        ),
        migrations.AlterField(
            model_name="property",
            name="address",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="main.address"
            ),
        ),
        migrations.AlterField(
            model_name="review",
            name="ending_rent",
            field=models.IntegerField(
                blank=True,
                null=True,
                validators=[django.core.validators.MaxValueValidator(999999)],
            ),
        ),
        migrations.AlterField(
            model_name="review",
            name="pub_date",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="review",
            name="starting_rent",
            field=models.IntegerField(
                blank=True,
                null=True,
                validators=[django.core.validators.MaxValueValidator(999999)],
            ),
        ),
        migrations.AlterField(
            model_name="review",
            name="user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterUniqueTogether(
            name="review",
            unique_together={
                (
                    "property",
                    "user",
                    "starting_rent_month_year",
                    "ending_rent_month_year",
                )
            },
        ),
        migrations.RemoveField(
            model_name="review",
            name="rented_duration",
        ),
    ]
