# Generated by Django 4.1.7 on 2023-04-01 15:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0003_rename_reviewed_property_review_property_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="review",
            name="title",
            field=models.CharField(default="", max_length=100),
        ),
    ]
