# Generated by Django 4.1.7 on 2023-04-02 14:05

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0004_alter_review_title"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="review",
            name="rented_duration_in_months",
        ),
    ]
