# Generated by Django 4.1.7 on 2023-04-02 15:55

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0005_remove_review_rented_duration_in_months"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="address",
            name="zip_code",
        ),
    ]
