# Generated by Django 4.1.7 on 2023-04-15 22:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0006_remove_address_zip_code"),
    ]

    operations = [
        migrations.AddField(
            model_name="address",
            name="full_address",
            field=models.CharField(default=None, max_length=400),
            preserve_default=False,
        ),
    ]
