# Generated by Django 4.1.7 on 2023-04-16 14:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0007_address_full_address"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="address",
            name="street_name",
        ),
        migrations.RemoveField(
            model_name="address",
            name="street_number",
        ),
        migrations.AddField(
            model_name="address",
            name="street",
            field=models.CharField(default=None, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="address",
            name="full_address",
            field=models.CharField(max_length=300),
        ),
    ]
