# Generated by Django 4.1.7 on 2023-03-18 18:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("property", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="review",
            old_name="property",
            new_name="reviewed_property",
        ),
        migrations.AlterField(
            model_name="property",
            name="reviews",
            field=models.ManyToManyField(to="property.review"),
        ),
    ]
